export default {
  home: "/",
  login: "/login",
  terms: "/terms",
  app: "/app",
  team: "/app/team/:id",
  settings: "/app/settings",
  me: "/settings/me",
  invite: "/invite/:code",
  timezone: "/app/tz/:id",
  meetings: "/app/meetings",
  newMeeting: "/app/meetings/new",
  meeting: "/app/meetings/:id",
  editMeeting: "/app/meetings/:id/edit",
};
