export default {
  home: "/",
  login: "/login",
  terms: "/terms",
  app: "/app",
  team: "/app/team/:id",
  settings: "/app/settings",
  me: "/settings/me",
  invite: "/invite/:code",
  timezone: "/app/tz/:id",
  meetings: "/app/calendar",
  newMeeting: "/app/calendar/new",
  meeting: "/app/calendar/:id",
  editMeeting: "/app/calendar/:id/edit",
  timer: "/app/timers/:id",
  timers: "/app/timers",
  newTimer: "/app/timers/new",
  editTimer: "/app/timers/:id/edit",
};
